use sporkify_db;


insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Konopelski, Heaney and Dare', 'Span', 'Cogilith', 'Comedy|Musical|Romance', 15041, '2008-04-24');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Feeney, Mosciski and Ankunding', 'Biodex', 'Ntag', 'Drama|Romance|Thriller', 2259, '2004-02-20');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Osinski, Bauch and Botsford', 'Mat Lam Tam', 'Centidel', 'Drama|War', 370, '1987-05-10');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hansen-Bogisich', 'Flowdesk', 'Skilith', 'Comedy|Horror|Mystery|Thriller', 7459, '2019-07-31');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Ratke, Schmitt and Wolf', 'Gembucket', 'Twimbo', 'Comedy|Drama', 4160, '2006-10-03');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Romaguera LLC', 'Viva', 'Yozio', 'Comedy|Drama', 9577, '1981-04-29');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Kutch, Wuckert and Schaden', 'Zoolab', 'Vitz', 'Documentary', 3231, '2010-03-27');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Glover LLC', 'Solarbreeze', 'Mymm', 'Comedy|Drama', 7412, '1984-06-06');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Lebsack and Sons', 'Cardguard', 'Blogtag', 'Crime|Drama|Thriller', 16811, '1999-01-13');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Torphy, DuBuque and Quitzon', 'Duobam', 'Jabberbean', 'Drama|Romance', 4677, '2002-11-05');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Zboncak-Raynor', 'Domainer', 'Zoomlounge', 'Action|Adventure', 13008, '2019-03-11');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Schiller LLC', 'Bitchip', 'Tagfeed', 'Drama|Romance|Sci-Fi', 7188, '2011-06-10');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Ryan and Sons', 'Greenlam', 'Oyoyo', 'Comedy|Crime|Romance', 13190, '2014-11-29');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Lesch, Cruickshank and Kulas', 'Ventosanzap', 'Zoomzone', 'Horror|Sci-Fi', 3940, '1990-12-05');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Johnson-Davis', 'Sub-Ex', 'Ntags', 'Drama', 7238, '2012-02-18');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Gibson LLC', 'Mat Lam Tam', 'Skyba', 'Comedy|Drama|Fantasy|Musical', 6706, '2019-12-30');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('DuBuque and Sons', 'Vagram', 'Aimbu', 'Documentary', 16183, '1986-09-16');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Corwin, Erdman and Pouros', 'Matsoft', 'Gabvine', 'Documentary', 6371, '2001-10-08');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Toy-Swaniawski', 'Sub-Ex', 'Buzzdog', 'Animation|Comedy|Fantasy', 15641, '1985-03-06');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Russel-Little', 'Konklux', 'Riffpedia', 'Action|Crime|Drama', 7699, '2003-01-04');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Dickens and Sons', 'Daltfresh', 'Oba', 'Action|Crime|Drama', 9724, '2017-09-12');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Strosin, Cassin and Herzog', 'Overhold', 'Meezzy', 'Western', 4351, '2010-09-28');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Swaniawski, Collier and Schinner', 'Konklab', 'Thoughtbridge', 'Drama', 1051, '2014-04-01');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Pacocha Group', 'Alphazap', 'Oloo', 'Thriller', 9898, '2000-07-08');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Tromp-Schulist', 'It', 'Divavu', 'Action|Drama|War', 6156, '1995-08-25');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Legros-Glover', 'Home Ing', 'Skivee', 'Action|Thriller', 14692, '2009-12-09');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hilll and Sons', 'Flexidy', 'Kwimbee', 'Children|Drama|Fantasy', 7733, '2014-05-26');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Fritsch Group', 'Tres-Zap', 'Katz', 'Action', 3663, '2003-07-26');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Stracke LLC', 'Aerified', 'Yombu', 'Drama|Fantasy|Thriller', 15750, '2015-02-10');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Kiehn, Reichert and Greenholt', 'Viva', 'Livetube', 'Comedy|Romance', 13812, '1991-11-16');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Fisher and Sons', 'Home Ing', 'Oyonder', 'Comedy|Drama', 15749, '1993-05-12');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Cole-Spinka', 'Fixflex', 'Voomm', 'Drama|Mystery', 16531, '2003-12-02');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Olson, Thiel and Ankunding', 'Konklab', 'Jaxworks', 'Comedy|Romance', 15865, '2003-03-26');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Jaskolski Group', 'Tempsoft', 'Shufflebeat', 'Drama|Romance', 12993, '1993-03-10');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Orn-Mitchell', 'Redhold', 'Mydo', 'Documentary|War', 17106, '1995-05-22');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Kub, Schroeder and King', 'Temp', 'Roomm', 'Action|Adventure|Comedy|Romance', 3093, '1997-04-08');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Kihn Inc', 'Toughjoyfax', 'Flashpoint', 'Drama|Film-Noir|Thriller', 201, '2019-10-25');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Pouros-Schiller', 'Trippledex', 'Livepath', 'Crime|Drama', 12679, '2000-11-01');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Schiller, Jakubowski and Roob', 'Bigtax', 'Feedfire', 'Drama|Fantasy|Romance|Sci-Fi', 11908, '1980-03-15');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Lehner, Nolan and Cassin', 'It', 'Demizz', 'Drama', 17289, '1991-10-28');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Kiehn, Bosco and Nicolas', 'Tin', 'Wordpedia', 'Comedy|Drama', 1024, '1991-12-27');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Streich LLC', 'Holdlamis', 'Rhybox', 'Drama|Romance|War', 2857, '2003-09-10');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Ondricka LLC', 'Ventosanzap', 'Dabfeed', 'Adventure|Animation|Children|Comedy', 3572, '1989-08-16');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Toy-Feest', 'Trippledex', 'Vitz', 'Horror', 8333, '2000-01-04');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Morissette, Little and Walsh', 'Tres-Zap', 'Edgepulse', 'Drama', 8202, '1984-08-20');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hermiston and Sons', 'Zoolab', 'Mydo', 'Mystery|Thriller', 11706, '2005-03-25');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Leffler LLC', 'Subin', 'Linkbridge', 'Action|Adventure|Sci-Fi', 3053, '1988-06-06');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Corkery, Medhurst and Rohan', 'Flowdesk', 'Yamia', 'Drama|Romance|War', 7225, '2007-03-07');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Heller, Fisher and Dibbert', 'Voyatouch', 'Photobean', 'Drama|Horror|Thriller', 323, '2015-05-24');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hahn and Sons', 'Opela', 'Realpoint', 'Drama|Romance', 15077, '2004-06-06');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hoppe-Renner', 'Solarbreeze', 'Einti', 'Action|Adventure|Sci-Fi', 15287, '2010-07-07');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Stoltenberg LLC', 'Vagram', 'Oyoba', 'Drama', 14917, '2008-11-06');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Macejkovic, Smith and Wuckert', 'Tempsoft', 'Tekfly', 'Action|Comedy|Fantasy', 7495, '1980-10-25');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Kozey Group', 'Voltsillam', 'Oba', 'Drama', 6994, '1996-08-01');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Koelpin, Rutherford and Klein', 'Flowdesk', 'Talane', 'Horror|Thriller', 3434, '1984-08-30');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Cronin and Sons', 'Andalax', 'Flashset', 'Comedy|Drama', 7565, '1995-05-14');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Morar-Wilderman', 'Fintone', 'Thoughtbridge', 'Drama', 14998, '1987-01-20');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Lubowitz, Jenkins and Kerluke', 'Pannier', 'Trilith', 'Drama', 17183, '2003-12-15');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Gerhold-Cole', 'Domainer', 'Viva', 'Thriller', 10801, '2003-01-24');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Schuppe-Rodriguez', 'Bytecard', 'Realfire', 'Action|Adventure|Thriller', 748, '1983-09-01');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Effertz-Grady', 'Mat Lam Tam', 'Dazzlesphere', 'Documentary', 3675, '2000-04-25');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Schmidt Group', 'Cardguard', 'Trudeo', 'Horror', 15102, '1990-06-07');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Lemke, Ratke and Conroy', 'Trippledex', 'Aivee', 'Comedy|Crime|Thriller', 473, '2016-03-01');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Aufderhar and Sons', 'Konklux', 'Mita', 'Drama', 3073, '2016-10-23');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Haley and Sons', 'Veribet', 'Aimbo', 'Drama|Horror|Thriller', 16197, '2016-10-24');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Lockman LLC', 'Namfix', 'Tagcat', 'Drama', 15016, '2009-07-24');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Kihn, Thiel and Champlin', 'Quo Lux', 'Jabberstorm', 'Action|Animation|Children|Comedy|IMAX', 8838, '1981-10-20');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Schulist, Feeney and Morar', 'Transcof', 'Jaloo', 'Action|Crime|Thriller', 10241, '1980-10-15');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hagenes, McClure and Feeney', 'Tempsoft', 'Twimbo', 'Drama', 12194, '1990-07-14');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hand-Grady', 'Pannier', 'Bubblebox', 'Drama', 2528, '1993-04-17');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Heathcote-Daniel', 'Tempsoft', 'Jabbersphere', 'Drama', 13062, '2019-07-15');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Pagac-Schmidt', 'Stronghold', 'Mynte', 'Action|Comedy', 9584, '1989-11-20');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hudson, Muller and Zboncak', 'Matsoft', 'Fliptune', 'Documentary', 16246, '1983-03-16');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Rogahn-Powlowski', 'Mat Lam Tam', 'Trupe', 'Drama|Romance', 11017, '2005-07-16');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Halvorson, Parker and Kemmer', 'Andalax', 'Muxo', 'Drama', 8200, '2018-05-31');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Shanahan, Barton and Bayer', 'Prodder', 'Chatterpoint', 'Drama', 2568, '1992-06-27');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Parker Inc', 'Fintone', 'Rhyloo', 'Drama|Romance|Western', 16247, '1992-06-07');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Schmitt and Sons', 'Otcom', 'Trudoo', 'Comedy', 12620, '2009-12-30');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Carter-Ward', 'Solarbreeze', 'Topicshots', 'Comedy', 10348, '2015-12-20');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Stehr-Klein', 'Bytecard', 'Jaxbean', 'Drama|Horror|Mystery', 4363, '1980-11-09');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Hauck-Ebert', 'Bamity', 'Flipbug', 'Action|Comedy', 10269, '1989-07-03');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Yost and Sons', 'Home Ing', 'Jaxnation', 'Drama', 13421, '1984-12-18');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Will Group', 'Sub-Ex', 'Skinix', 'Drama|Thriller', 6564, '2004-12-22');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Bernier, Nienow and Leffler', 'Y-find', 'Mita', 'Documentary', 6339, '1988-02-15');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Cole-Tillman', 'Zamit', 'Aimbo', 'Crime|Drama', 6553, '1985-12-04');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Heidenreich, McClure and Farrell', 'Y-find', 'Dynava', 'Action|Comedy', 1177, '2019-03-27');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('DuBuque-Bogisich', 'Gembucket', 'Jayo', 'Drama|Romance', 14536, '2015-01-11');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Bahringer Group', 'Viva', 'Zooveo', 'Drama', 15877, '1983-05-01');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Rosenbaum, Gulgowski and O''Conner', 'Zoolab', 'Thoughtsphere', 'Documentary', 7133, '2011-08-29');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Zboncak, Rosenbaum and Lind', 'Opela', 'Chatterbridge', 'Adventure|Comedy', 3194, '1992-08-12');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Fritsch, Mohr and O''Kon', 'Stringtough', 'Buzzdog', '(no genres listed)', 10546, '1992-06-23');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Dickens, Baumbach and Haley', 'Bytecard', 'Cogibox', 'Comedy', 17758, '1997-10-15');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Rippin-Kirlin', 'Kanlam', 'Yamia', 'Documentary', 12924, '1997-07-18');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Altenwerth-Schamberger', 'Sub-Ex', 'Yotz', 'Drama|Romance|Thriller', 3892, '2003-03-28');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Aufderhar, Cummerata and Windler', 'Zontrax', 'Kayveo', 'Drama', 17446, '1984-12-05');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Kling-Huels', 'Konklab', 'Jabberbean', 'Animation|Musical', 9363, '2000-01-14');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Conn Inc', 'Mat Lam Tam', 'Gigazoom', 'Crime|Drama', 4526, '1984-04-16');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Walter Group', 'Namfix', 'Jayo', 'Comedy|Horror', 16644, '2001-10-06');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Boehm Group', 'Duobam', 'Vitz', 'Comedy|Drama', 3311, '1990-11-15');
insert into SPORKIFY (artist, album, song, genre, duration, release_date) values ('Watsica LLC', 'Aerified', 'Voonder', 'Crime|Drama', 986, '1981-03-24');
